### ISSUE TITLE
Slight Design Changes

### ISSUE THREAD

**Issue by zhixinlin** [freethlua/individualogist-whats-your-archetype#52] opened 2017-07-26 13:53 UTC
Hi Freeth,

Please refer to attached PSD file for mild changes to the following:

1. Glow in name tag for "[testname's] archetype reading". Please add the following css to a specified div class for [testname]:
{
text-shadow: 0 0 10px #fff, 0 0 20px #fff, 0 0 30px #d611ff, 0 0 40px #d611ff, 0 0 70px #d611ff, 0 0 80px #d611ff, 0 0 100px #d611ff, 0 0 150px #d611ff;
}

2. Change to FB Comments call to action, "What archetype did you get? Let us know in the comments below!". Please place text in div container with the styles, font (or similar), and colours as seen in the PSD file. Thanks, Freeth!

[what archetype did you get.psd.zip](https://github.com/freethlua/individualogist-whats-your-archetype/files/1176763/what.archetype.did.you.get.psd.zip)

**Comment by zhixinlin** [comment] 2017-07-31 08:10
Hi Freeth,

Please also change the fonts to be consistent (note the testimonial area)

Perhaps set all fonts to Nunito/sans-serif, thanks :)

**Comment by zhixinlin** [comment] 2017-08-07 05:50
Hi Freeth,

Please make the following amendments to the above changes, compiled everything into the summary below:

Testimonial:
- Change font family of headers to Nunito/sans-serif
- Increase line height of paragraph tags to 1.5em 

FAQ
- Change font size of headers/questions to 1.2em
- Change line height of paragraph/answers to 1.5em

FB Comments CTA
- Purple arrow pointing down isn't centred, I'm guessing margin-left should be approximately 35%. 

After all these changes are made, please proceed to migrate/copy all of these design changes (including the glowing text) to master (archetype.individualogist.com). 

That should be all for this issue, thanks Freeth!

**Comment by freethlua** [comment] 2017-08-07 09:00
Done

**Comment by zhixinlin** [comment] 2017-08-07 09:42
Hi Freeth,

Just to add on to this, please also proceed to implement the pop up overlays to the master folder as well; so pretty much all changes should be transferred over to the master. Thanks!

**Comment by freethlua** [comment] 2017-08-07 11:05
All done. Please test all once more (everything from start possibly, using `?new` in the URL to finish) and give me a final confirmation to move to from staging to master.

**Comment by zhixinlin** [comment] 2017-08-07 11:34
Hi Freeth,

That was quick! Awesome, very appreciative of your swift action! Just a couple of issues we encountered:

1. Text is slightly out of sync with v/o
2. Please implement "text-transform: capitalize" for overlay buttons ("yes please tell me more about individuation")
3. Slight mobile optimization issues as seen in screenshot below (iPhone 6 Safari):
- Name tag and logo positioned below instead of at the top of page
- Youtube video extending beyond device width, creating white space on the right
- Increase video font size for mobile device
![img-9327](https://user-images.githubusercontent.com/19595715/29024965-17a179da-7ba7-11e7-8775-6c16ccb47377.PNG)

That should be all and we'll be good to go, thanks Freeth!

**Comment by freethlua** [comment] 2017-08-09 13:43
Fixed the following issues: 

1. > Text is slightly out of sync with v/o

    It was probably only occurring when using the query strings `?seekTo=...`. Although that should be fixed too now. Please test again. 

2. > Implement "text-transform: capitalize" for overlay buttons ("yes please tell me more about individuation")

    done

3. > Slight mobile optimization issues as seen in screenshot below (iPhone 6 Safari):

    - > Name tag and logo positioned below instead of at the top of page

        Really not sure how this is getting messed up, worse part is I can't even reproduce it locally. 

        The logo only jumps to the bottom when displaying the lover-compatibility chart, so my guess would be it's probably due to some jumping ahead issue related to that (probably linked to using `?seekTo=...`)

        Please try again and let me know more details such as 

        1. Does it happen from the beginning, or only after a certain trigger like reaching the deluxe report. 
        2. Are you using `?seekTo=...`, if so please try without it

        ---

     - > Youtube video extending beyond device width, creating white space on the right

        done

     - > Increase video font size for mobile device

        done

**Comment by wilsonljx** [comment] 2017-08-10 11:52
Hi Freeth

Aaron here, just tested out number 3 - you're right, can't replicate the issue again. It's probably nothing, let's leave it for now. Everything else is great.

![untitled](https://user-images.githubusercontent.com/29788050/29169171-3451ce44-7e05-11e7-9f23-48ffe917f75a.png)

Just one more small change, please put the text "everything you need to know about... we've prepared a free detailed... love, health and wealth just for you" between h1/h2 tags to enlarge font size. 

Once that's done, please proceed to close the issue and migrate all changes to master and leave a comment to let us know that changes are migrated - no need for any further checks. Thanks, Freeth!

**Comment by freethlua** [comment] 2017-08-13 10:51
All done. 

Regarding above h1/h2 (and related odd css issues cropping up lately) they actually already were h1/h2 but earlier I had included a ["reset" css](https://www.npmjs.com/package/reset-css) that was meant to normalize certain css properties across different devices and it actually reset some unwanted stuff, like the above h1/h2 as well as some other things like line-heights in p elements. Sorry about that. I've now added the bootstrap's version of the same namely [reboot.css](https://v4-alpha.getbootstrap.com/content/reboot/) which seems much better. 

There's also been some major changes (#56) so please test the entire app once again.

**Closed as completed** 2017-08-28 18:36 UTC
